# secrets.toml

[GCP_CREDENTIALS]
type                         = "service_account"
project_id                   = "gemini-demo-467504"
private_key_id               = "ca7268cb4985da6a4188f23f68850d149a24b34"
private_key                  = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCXk9XWV5osBUc9
Q5pzjin59/gYJxmtPHs3N05tjmk37oCHW93emN5yBhe5Ig07LgJ4M0UUqIBMpWN+
FujpCTojYY12BLadf0BDyLAUN27imHags+TPAL9ZmMNPRjmiAbnf32EssrcJCBa7
bs0in5m+f9anWtA6gGbkaPzxsA1aP0AqVCFyz7EC+UXcve4FPeirO49zvUsw8Wwc
B4XccbZAcuDORGht0NdSK1OnBx+qYVpW78+2MPsHqb2Uma9fSedhlRvcXPTFH8oP
a2S/3zBdGyQVU+u116nZVG6PqRgkRJoyrqXqAzVeI4JpMvTTmwEQpE9hOC+yOhIz
VA18HZkJAgMBAAECggEAPC0Cvd91Y3iM+bN3A90yqPxa0Cvls7LJL/iS+EeLWhsj
h5lfEdoapaXpkSQFoLL5ZALmr/bdSJB4WTx7Jtj07crywCHK5ef4+XAZB02ihe8F
WXNRqSSg0s8k6rn0c26//jLOf1JL/Bfr/mlUoyQ9gzV5YGNbO35yWsebc8/y3RqW
aFrgUSgeI6sbtYSURNR5jx3f9lMF6pgqhdce4ynNAky2RHu8OyKRM6qImugnguhv
k6V9QXMjNOlgW2nz9XuB0rQWp8EVEJAOQuC47EsSRzwfg9UL/vZt1BtubSDwBBF1
OLJHk88CafXypfqmkA7rbd4ifEbbfmEwANHu12cUqQKBgQDT+XKxLQsWp12PtkCa
jfHjBGgv2xIpPOadhmwQ45TQQTgYc6v2d6vUU/R3vQge++uNeRWzcUIFTXxRXbnT
d4PKZYI1caXoJt7uB2FGw6PzpdUpb97V+/kaSiZeMKlovhD4sMkMEVUApsTH6zCe
MIL5CQ0UypehS//9ZLawmNYH/wKBgQC3Dx55qLA+ESG/yWgTPZd8aqJX3FVzA3gw
lY0944E2t8x6YAvkmdf8awU1AUS9Y72faHVJo5qNMY/w/5MFGTE7K3D4ca8SRPrV
qn8/IkU1aX/Or0B3O9zSPr2iZq4B4eMr9xGUgzrY59rQ90u3BCyFnHvkRgynTOTK
Q5/xr1Qe9wKBgEXBvkOeHhsLYtfLU0FJWwOpTJwLDNPzTbUjKmb4bd2GyO4LCtkm
Eq7iHf5Vf9mqb57z7PdLWz2hfTrNjDySBRXTB+GMj9txB0Xvucxuz4J73UUwonVq
4VQMeMngW6+zdKRSkSbegUmgl/tuY2Z7cm5/0wU3kmSrPQfnX9OHyE+DAoGBAIa1
XoTCaOdTrhU2/hpika5hvhOPtWXMoM6HzwdC+pwshxFqynWv7Gv4yT0nMNF5q1m6
Ac1t0laiqTz8pdDzp/HV1u1Mozt7fWZsb/Uin/FdMEsFVhgn+ijROLVggB4sfwKk
btBt/YkOnUx3HsWQEb9E1zq1faxDfn2FZBbzIaEjAoGARL5f7/IJTkpNOQeLHSXC
fud2LWscVgJnvhucemSlceiWdpsmKk4GrGEIw7PPYmZEZ8ezc/VaFQhP+HCihiE5
vl11bEF4VSCs1TVYOrUocVK04BE/bAQjSXeIrQhbWxF3QX56wPOG2kQHRxyfe+Ct
1YAr7nDKlCq1km4CWvtWoPY=
-----END PRIVATE KEY-----"""
client_email                 = "gemini@gemini-demo-467504.iam.gserviceaccount.com"
client_id                    = "108992252933656164636"
auth_uri                     = "https://accounts.google.com/o/oauth2/auth"
token_uri                    = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url  = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url         = "https://www.googleapis.com/robot/v1/metadata/x509/gemini%40gemini-demo-467504.iam.gserviceaccount.com"
universe_domain              = "googleapis.com"
